FROM ubuntu:20.04

# USER root
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y
RUN apt-get install -y git wget cmake gcc g++ cpp curl software-properties-common

# INSTALL NODEJS SERVER
RUN apt-get update -y
RUN curl -sL https://deb.nodesource.com/setup_19.x | bash
RUN apt-get install -y nodejs
#RUN npm install pm2 -g

# Create app directory
COPY . ./maip-app

RUN cd maip-app/src/client && npm install --force

WORKDIR ./maip-app/

EXPOSE 3000
CMD ./start-client.sh